// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.20.2")]
[assembly: AssemblyFileVersionAttribute("1.20.2")]
[assembly: AssemblyTrademarkAttribute("n/a")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.20.2";
        internal const System.String AssemblyFileVersion = "1.20.2";
        internal const System.String AssemblyTrademark = "n/a";
    }
}
