// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.20.2")]
[assembly: AssemblyFileVersionAttribute("1.20.2")]
[assembly: AssemblyTrademarkAttribute("201af06ff5eea18c66889ec7e46548346f119b17")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.20.2";
        internal const System.String AssemblyFileVersion = "1.20.2";
        internal const System.String AssemblyTrademark = "201af06ff5eea18c66889ec7e46548346f119b17";
    }
}
